# Generated by Django 4.2.7 on 2025-10-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('arts', 'Arts & Music'), ('volunteer', 'Volunteering'), ('club', 'Clubs & Organizations'), ('creative', 'Creative Pursuits'), ('other', 'Other')], default='other', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements or roles')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
                'ordering': ['-is_current', '-start_date', 'order'],
            },
        ),
    ]
