# Generated by Django 4.2.7 on 2025-10-24 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Award or accomplishment title', max_length=200)),
                ('issuer', models.CharField(help_text='Issuing organization or institution', max_length=200)),
                ('date', models.DateField(help_text='Date received')),
                ('category', models.CharField(choices=[('academic', 'Academic Achievement'), ('professional', 'Professional Recognition'), ('competition', 'Competition/Contest'), ('scholarship', 'Scholarship'), ('leadership', 'Leadership'), ('community', 'Community Service'), ('publication', 'Publication'), ('patent', 'Patent'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Details about the award or accomplishment')),
                ('url', models.URLField(blank=True, help_text='Link to certificate or announcement', validators=[django.core.validators.URLValidator()])),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
    ]
