# Generated by Django 4.2.7 on 2025-10-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(help_text="Display label (e.g., 'Work Email', 'Personal Phone')", max_length=100)),
                ('value', models.CharField(help_text='Email address, phone number, or URL', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary contact method')),
                ('is_public', models.BooleanField(default=True, help_text='Show on public portfolio')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'contact_type'],
            },
        ),
    ]
