# Generated by Django 4.2.7 on 2025-10-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.TextField(help_text='Comma-separated list of authors')),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('thesis', 'Thesis/Dissertation'), ('preprint', 'Preprint'), ('magazine', 'Magazine Article'), ('blog', 'Blog Post'), ('other', 'Other')], default='journal', max_length=50)),
                ('publisher', models.CharField(blank=True, help_text='Journal/Conference/Publisher name', max_length=200)),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Link to the publication')),
                ('description', models.TextField(blank=True, help_text='Abstract or summary')),
                ('citation_count', models.IntegerField(blank=True, default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-publication_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('inventors', models.TextField(help_text='Comma-separated list of inventors')),
                ('patent_number', models.CharField(blank=True, help_text='Patent/Application number', max_length=100)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('pending', 'Pending'), ('filed', 'Filed'), ('published', 'Published'), ('expired', 'Expired')], default='filed', max_length=50)),
                ('filing_date', models.DateField()),
                ('issue_date', models.DateField(blank=True, help_text='Date patent was granted', null=True)),
                ('patent_office', models.CharField(blank=True, help_text='e.g., USPTO, EPO, etc.', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Link to patent details')),
                ('description', models.TextField(blank=True, help_text='Patent abstract or summary')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-filing_date', 'order'],
            },
        ),
    ]
