# Generated by Django 4.2.7 on 2025-10-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_publication_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="Custom category name (e.g., 'Volunteer Work', 'Press', 'Media')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, help_text='Relevant date for this item', null=True)),
                ('url', models.URLField(blank=True, help_text='Related link')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Other Item',
                'verbose_name_plural': 'Other Items',
                'ordering': ['order', '-date', '-created_at'],
            },
        ),
    ]
