# Generated by Django 4.2.7 on 2025-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
