# Generated by Django 4.2.7 on 2025-10-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Parsed resume data in structured JSON format', null=True),
        ),
    ]
