# Generated by Django 4.2.7 on 2025-12-02 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_parser', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the cover letter (e.g., role name)', max_length=200)),
                ('role', models.CharField(blank=True, help_text='Job role applied for', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('content', models.TextField(help_text='Cover letter content')),
                ('template_style', models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('creative', 'Creative'), ('header', 'Header Style')], default='professional', max_length=50)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('font_size', models.CharField(choices=[('small', 'Small (11pt)'), ('medium', 'Medium (12pt)'), ('large', 'Large (13pt)')], default='medium', max_length=20)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('justify', 'Justify')], default='left', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='resume_parser.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
