# Generated by Django 4.2.7 on 2025-10-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Cover letter title/identifier', max_length=200)),
                ('role', models.CharField(help_text='Job role/position', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Target company', max_length=200)),
                ('job_description', models.TextField(help_text='Job description provided by user')),
                ('additional_info', models.TextField(blank=True, help_text='Additional user-provided information')),
                ('generated_content', models.TextField(help_text='AI-generated cover letter content')),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether user has finalized the letter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cover Letter',
                'verbose_name_plural': 'Cover Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
